import type {
  DeltaOperation,
  TokenUsage,
  UndoHandle,
} from '../services/llm/types'

/**
 * Chronicle System Types - Core data structures for narrative note-taking
 * Hybrid Narrative Chronicle + Campaign Wiki implementation
 */

export type EntityType =
  | 'character'
  | 'location'
  | 'organization'
  | 'item'
  | 'event'
  | 'mystery'
  | 'relationship'

export type RelationshipType =
  | 'ally'
  | 'enemy'
  | 'family'
  | 'romantic'
  | 'business'
  | 'mentor'
  | 'unknown'

export type NarrativeContext =
  | 'setup'
  | 'action'
  | 'consequence'
  | 'reflection'
  | 'description'

export type EmotionalTone =
  | 'tense'
  | 'triumphant'
  | 'mysterious'
  | 'somber'
  | 'funny'
  | 'neutral'

export type EntityStatus =
  | 'active'
  | 'resolved'
  | 'dormant'
  | 'unknown'
  | 'deceased'

// Core chronicle entry - the fundamental unit of story
export interface ChronicleEntry {
  id: string
  sessionId: string
  campaignId?: string
  timestamp: Date
  rawText: string
  parsedEntities: EntityMention[]
  narrativeContext?: NarrativeContext
  emotionalTone?: EmotionalTone
  tags: string[]
  previousEntry?: string
  nextEntry?: string
  isSceneBreak: boolean
  userNotes?: string // Additional context added by user
}

// Reference to an entity within chronicle text
export interface EntityMention {
  entityId: string
  mentionText: string // The actual text that was typed (@Baron Redcloak)
  startIndex: number
  endIndex: number
  confidence: number // How confident we are this is the right entity (0-1)
  context: string // Surrounding text for disambiguation
}

// Core entity - represents any important campaign element
export interface Entity {
  id: string
  name: string
  type: EntityType
  description: string
  firstMention: string // ChronicleEntry ID
  lastMention: string // ChronicleEntry ID
  appearances: string[] // Array of ChronicleEntry IDs
  relationships: Relationship[]
  aliases: string[] // Alternative names
  status: EntityStatus
  tags: string[]
  importance: number // Calculated based on mention frequency and recency (0-100)
  createdAt: Date
  lastUpdated: Date
  userNotes?: string // User-added description/details
}

// Relationship between two entities
export interface Relationship {
  id: string
  fromEntityId: string
  toEntityId: string
  type: RelationshipType
  strength: number // -10 to +10, negative for antagonistic
  description?: string
  history: RelationshipEvent[]
  currentStatus: string
  confidence: number // How sure we are about this relationship (0-1)
  createdAt: Date
  lastUpdated: Date
}

// Evolution of a relationship over time
export interface RelationshipEvent {
  id: string
  chronicleEntryId: string
  description: string
  strengthChange: number
  timestamp: Date
  eventType: 'meeting' | 'conflict' | 'alliance' | 'betrayal' | 'other'
}

// Auto-generated wiki page for each entity
export interface WikiPage {
  entityId: string
  autoGeneratedSummary: string
  keyFacts: WikiFact[]
  timeline: WikiTimelineEntry[]
  relationshipSummary: string
  mysteries: string[] // Unresolved questions about this entity
  userContent: string // User-added content
  lastGenerated: Date
  viewCount: number
  bookmarked: boolean
}

// Individual facts extracted from chronicle entries
export interface WikiFact {
  id: string
  fact: string
  chronicleEntryId: string
  confidence: number
  factType: 'description' | 'action' | 'dialogue' | 'location' | 'relationship'
  extractedAt: Date
}

// Timeline entry for entity wiki
export interface WikiTimelineEntry {
  id: string
  chronicleEntryId: string
  description: string
  timestamp: Date
  importance: number // 1-5, how significant this event was
  entityRole: 'primary' | 'secondary' | 'mentioned' // How involved the entity was
}

// Search result for chronicle content
export interface ChronicleSearchResult {
  type: 'entry' | 'entity' | 'relationship'
  id: string
  title: string
  excerpt: string
  relevanceScore: number
  matchedTerms: string[]
  contextBefore?: string
  contextAfter?: string
}

// Narrative thread detection
export interface NarrativeThread {
  id: string
  title: string
  description: string
  chronicleEntries: string[]
  relatedEntities: string[]
  status: 'active' | 'resolved' | 'dormant'
  importance: number
  firstEntry: string
  lastEntry: string
  threadType: 'mystery' | 'character_arc' | 'plot' | 'worldbuilding'
}

// Parser configuration and results
export interface ParseResult {
  entities: EntityMention[]
  relationships: InferredRelationship[]
  narrativeContext?: NarrativeContext
  emotionalTone?: EmotionalTone
  isSceneBreak: boolean
  extractedTags: string[]
  confidence: number
}

// Relationship inferred from text analysis
export interface InferredRelationship {
  fromEntityId: string
  toEntityId: string
  type: RelationshipType
  confidence: number
  evidence: string // The text that suggested this relationship
  chronicleEntryId: string
}

// Settings for chronicle behavior
export interface ChronicleTelemetryEventLog {
  id: string
  recordedAt: string
  stage: 'propose' | 'apply' | 'undo' | 'guardrail'
  outcome: 'success' | 'failure' | 'skipped'
  model: string
  latencyMs: number
  usage: TokenUsage
  costCents?: number
  bundleId?: string
  entryId?: string
  error?: string
  source: 'tauri' | 'client'
}

export interface ChronicleDeltaLog {
  bundleId: string
  entryId: string
  appliedOps: DeltaOperation[]
  skippedOps: DeltaOperation[]
  createdAt: string
  undoHandle?: UndoHandle
  actor?: 'auto' | 'manual' | 'system' | 'user'
  status?: 'pending' | 'applied' | 'undone' | 'failed'
  requestedAt?: string
  autoApply?: boolean
  durationMs?: number
  undoneAt?: string
  undoActor?: 'auto' | 'manual' | 'system' | 'user'
  error?: string
}

export type ChronicleAuditAction = 'applied' | 'undone' | 'failed'

export interface ChronicleAuditEntry {
  id: string
  bundleId?: string
  entryId: string
  action: ChronicleAuditAction
  actor?: 'auto' | 'manual' | 'system' | 'user'
  reason?: string
  timestamp: string
  appliedOps?: DeltaOperation[]
  skippedOps?: DeltaOperation[]
}

export interface PendingChronicleBundle {
  bundleId?: string
  entryId?: string
  requestedAt: string
  autoApply: boolean
  startedAt?: string
  status?: 'pending' | 'applying'
  actor?: 'auto' | 'manual' | 'system' | 'user'
}

export interface ChronicleBundleSnapshot {
  id: string
  bundleId: string
  entryId: string
  stage: 'before' | 'after'
  capturedAt: string
  actor: 'auto' | 'manual' | 'system' | 'user'
  autoApply: boolean
  metrics: {
    totalCharacters: number
    characters: Array<{
      id: string
      name: string
      hp: { current: number; max: number }
      xp: number
      coin: number
    }>
    inventory: {
      totalItems: number
      totalEquipped: number
      totalQuickSlots: number
      equippedItemIds: string[]
      quickSlotIds: string[]
    }
    holds: Array<{
      characterId: string
      holdId: string
      moveId: string
      moveName: string
      amount: number
      maxAmount: number
    }>
    totalHoldEntries: number
  }
}

export type ResourceLogType =
  | 'xp'
  | 'bond'
  | 'hold'
  | 'debility'
  | 'hp'
  | 'coin'
  | 'load'

export interface BaseResourceLogEntry {
  id: string
  bundleId: string
  entryId: string
  createdAt: string
  characterId: string
}

export interface XpLogEntry extends BaseResourceLogEntry {
  type: 'xp'
  amount: number
  previous: number
  next: number
  reason?: string
  note?: string
}

export interface HpLogEntry extends BaseResourceLogEntry {
  type: 'hp'
  delta: number
  previous: number
  next: number
  reason?: string
}

export interface CoinLogEntry extends BaseResourceLogEntry {
  type: 'coin'
  amount: number
  previous: number
  next: number
}

export interface LoadLogEntry extends BaseResourceLogEntry {
  type: 'load'
  delta: number
  previous: number
  next: number
  reason?: string
}

export interface BondLogEntry extends BaseResourceLogEntry {
  type: 'bond'
  bondId: string
  targetId?: string
  text: string
  action: 'add' | 'resolve'
  resolved: boolean
}

export interface HoldLogEntry extends BaseResourceLogEntry {
  type: 'hold'
  holdId: string
  moveId: string
  moveName: string
  change: number
  remaining: number
}

export interface DebilityLogEntry extends BaseResourceLogEntry {
  type: 'debility'
  debility: string
  action: 'add' | 'remove'
}

export type ResourceLogEntry =
  | XpLogEntry
 | HpLogEntry
 | CoinLogEntry
 | BondLogEntry
 | HoldLogEntry
 | DebilityLogEntry
 | LoadLogEntry

export interface ResourceHistoryState {
  xp: Record<string, XpLogEntry[]>
  bonds: Record<string, BondLogEntry[]>
  hold: Record<string, HoldLogEntry[]>
  debilities: Record<string, DebilityLogEntry[]>
  hp: Record<string, HpLogEntry[]>
  coin: Record<string, CoinLogEntry[]>
  load: Record<string, LoadLogEntry[]>
}

export interface ChronicleSettings {
  autoEntityCreation: boolean
  minimumConfidenceForAutoCreation: number
  enableVoiceInput: boolean
  enableSmartSuggestions: boolean
  parseOnType: boolean // Real-time vs on-save parsing
  defaultEntityTypes: EntityType[]
  customTags: string[]
  autoApplyPolicy: Record<string, 'auto' | 'confirm' | 'off'>
  tone: 'gritty' | 'heroic' | 'terse'
  verbosity: 'short' | 'standard' | 'long'
  costCapCents?: number
  autoEquipWeapons: boolean
}
