/**
 * Chronicle System Types - Core data structures for narrative note-taking
 * Hybrid Narrative Chronicle + Campaign Wiki implementation
 */

export type EntityType
  = | 'character'
    | 'location'
    | 'organization'
    | 'item'
    | 'event'
    | 'mystery'
    | 'relationship'

export type RelationshipType
  = | 'ally'
    | 'enemy'
    | 'family'
    | 'romantic'
    | 'business'
    | 'mentor'
    | 'unknown'

export type NarrativeContext
  = | 'setup'
    | 'action'
    | 'consequence'
    | 'reflection'
    | 'description'

export type EmotionalTone
  = | 'tense'
    | 'triumphant'
    | 'mysterious'
    | 'somber'
    | 'funny'
    | 'neutral'

export type EntityStatus
  = | 'active'
    | 'resolved'
    | 'dormant'
    | 'unknown'
    | 'deceased'

// Core chronicle entry - the fundamental unit of story
export interface ChronicleEntry {
  id: string
  sessionId: string
  campaignId?: string
  timestamp: Date
  rawText: string
  parsedEntities: EntityMention[]
  narrativeContext?: NarrativeContext
  emotionalTone?: EmotionalTone
  tags: string[]
  previousEntry?: string
  nextEntry?: string
  isSceneBreak: boolean
  userNotes?: string // Additional context added by user
}

// Reference to an entity within chronicle text
export interface EntityMention {
  entityId: string
  mentionText: string // The actual text that was typed (@Baron Redcloak)
  startIndex: number
  endIndex: number
  confidence: number // How confident we are this is the right entity (0-1)
  context: string // Surrounding text for disambiguation
}

// Core entity - represents any important campaign element
export interface Entity {
  id: string
  name: string
  type: EntityType
  description: string
  firstMention: string // ChronicleEntry ID
  lastMention: string // ChronicleEntry ID
  appearances: string[] // Array of ChronicleEntry IDs
  relationships: Relationship[]
  aliases: string[] // Alternative names
  status: EntityStatus
  tags: string[]
  importance: number // Calculated based on mention frequency and recency (0-100)
  createdAt: Date
  lastUpdated: Date
  userNotes?: string // User-added description/details
}

// Relationship between two entities
export interface Relationship {
  id: string
  fromEntityId: string
  toEntityId: string
  type: RelationshipType
  strength: number // -10 to +10, negative for antagonistic
  description?: string
  history: RelationshipEvent[]
  currentStatus: string
  confidence: number // How sure we are about this relationship (0-1)
  createdAt: Date
  lastUpdated: Date
}

// Evolution of a relationship over time
export interface RelationshipEvent {
  id: string
  chronicleEntryId: string
  description: string
  strengthChange: number
  timestamp: Date
  eventType: 'meeting' | 'conflict' | 'alliance' | 'betrayal' | 'other'
}

// Auto-generated wiki page for each entity
export interface WikiPage {
  entityId: string
  autoGeneratedSummary: string
  keyFacts: WikiFact[]
  timeline: WikiTimelineEntry[]
  relationshipSummary: string
  mysteries: string[] // Unresolved questions about this entity
  userContent: string // User-added content
  lastGenerated: Date
  viewCount: number
  bookmarked: boolean
}

// Individual facts extracted from chronicle entries
export interface WikiFact {
  id: string
  fact: string
  chronicleEntryId: string
  confidence: number
  factType: 'description' | 'action' | 'dialogue' | 'location' | 'relationship'
  extractedAt: Date
}

// Timeline entry for entity wiki
export interface WikiTimelineEntry {
  id: string
  chronicleEntryId: string
  description: string
  timestamp: Date
  importance: number // 1-5, how significant this event was
  entityRole: 'primary' | 'secondary' | 'mentioned' // How involved the entity was
}

// Search result for chronicle content
export interface ChronicleSearchResult {
  type: 'entry' | 'entity' | 'relationship'
  id: string
  title: string
  excerpt: string
  relevanceScore: number
  matchedTerms: string[]
  contextBefore?: string
  contextAfter?: string
}

// Narrative thread detection
export interface NarrativeThread {
  id: string
  title: string
  description: string
  chronicleEntries: string[]
  relatedEntities: string[]
  status: 'active' | 'resolved' | 'dormant'
  importance: number
  firstEntry: string
  lastEntry: string
  threadType: 'mystery' | 'character_arc' | 'plot' | 'worldbuilding'
}

// Parser configuration and results
export interface ParseResult {
  entities: EntityMention[]
  relationships: InferredRelationship[]
  narrativeContext?: NarrativeContext
  emotionalTone?: EmotionalTone
  isSceneBreak: boolean
  extractedTags: string[]
  confidence: number
}

// Relationship inferred from text analysis
export interface InferredRelationship {
  fromEntityId: string
  toEntityId: string
  type: RelationshipType
  confidence: number
  evidence: string // The text that suggested this relationship
  chronicleEntryId: string
}

// Settings for chronicle behavior
export interface ChronicleSettings {
  autoEntityCreation: boolean
  minimumConfidenceForAutoCreation: number
  enableVoiceInput: boolean
  enableSmartSuggestions: boolean
  parseOnType: boolean // Real-time vs on-save parsing
  defaultEntityTypes: EntityType[]
  customTags: string[]
}
